// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package sqlc

import (
	"context"

	uuid "github.com/google/uuid"
)

const insertAnalyticsEvent = `-- name: InsertAnalyticsEvent :exec
INSERT INTO analytics_events (user_id, game_id, event_type, payload)
VALUES ($1, $2, $3, $4)
`

type InsertAnalyticsEventParams struct {
	UserID    uuid.UUID `json:"user_id"`
	GameID    string    `json:"game_id"`
	EventType string    `json:"event_type"`
	Payload   []byte    `json:"payload"`
}

func (q *Queries) InsertAnalyticsEvent(ctx context.Context, arg InsertAnalyticsEventParams) error {
	_, err := q.db.Exec(ctx, insertAnalyticsEvent,
		arg.UserID,
		arg.GameID,
		arg.EventType,
		arg.Payload,
	)
	return err
}

const listEventsByUser = `-- name: ListEventsByUser :many
SELECT id, user_id, game_id, event_type, payload, created_at FROM analytics_events
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListEventsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListEventsByUser(ctx context.Context, arg ListEventsByUserParams) ([]AnalyticsEvent, error) {
	rows, err := q.db.Query(ctx, listEventsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsEvent{}
	for rows.Next() {
		var i AnalyticsEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GameID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
