// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package sqlc

import (
	"context"
)

const getGameByID = `-- name: GetGameByID :one
SELECT id, title, creator_id, time_limit_sec, tags, bundle_url, bundle_version, bundle_hash, created_at FROM games WHERE id = $1
`

func (q *Queries) GetGameByID(ctx context.Context, id string) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatorID,
		&i.TimeLimitSec,
		&i.Tags,
		&i.BundleUrl,
		&i.BundleVersion,
		&i.BundleHash,
		&i.CreatedAt,
	)
	return i, err
}

const listGames = `-- name: ListGames :many
SELECT id, title, creator_id, time_limit_sec, tags, bundle_url, bundle_version, bundle_hash, created_at FROM games ORDER BY id
`

func (q *Queries) ListGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatorID,
			&i.TimeLimitSec,
			&i.Tags,
			&i.BundleUrl,
			&i.BundleVersion,
			&i.BundleHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesByTags = `-- name: ListGamesByTags :many
SELECT id, title, creator_id, time_limit_sec, tags, bundle_url, bundle_version, bundle_hash, created_at FROM games WHERE tags && $1::text[] ORDER BY id
`

func (q *Queries) ListGamesByTags(ctx context.Context, dollar_1 []string) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGamesByTags, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatorID,
			&i.TimeLimitSec,
			&i.Tags,
			&i.BundleUrl,
			&i.BundleVersion,
			&i.BundleHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGame = `-- name: UpsertGame :exec
INSERT INTO games (id, title, creator_id, time_limit_sec, tags, bundle_url, bundle_version, bundle_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    creator_id = EXCLUDED.creator_id,
    time_limit_sec = EXCLUDED.time_limit_sec,
    tags = EXCLUDED.tags,
    bundle_url = EXCLUDED.bundle_url,
    bundle_version = EXCLUDED.bundle_version,
    bundle_hash = EXCLUDED.bundle_hash
`

type UpsertGameParams struct {
	ID            string   `json:"id"`
	Title         string   `json:"title"`
	CreatorID     string   `json:"creator_id"`
	TimeLimitSec  int32    `json:"time_limit_sec"`
	Tags          []string `json:"tags"`
	BundleUrl     string   `json:"bundle_url"`
	BundleVersion string   `json:"bundle_version"`
	BundleHash    string   `json:"bundle_hash"`
}

func (q *Queries) UpsertGame(ctx context.Context, arg UpsertGameParams) error {
	_, err := q.db.Exec(ctx, upsertGame,
		arg.ID,
		arg.Title,
		arg.CreatorID,
		arg.TimeLimitSec,
		arg.Tags,
		arg.BundleUrl,
		arg.BundleVersion,
		arg.BundleHash,
	)
	return err
}
