// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	uuid "github.com/google/uuid"
)

type AnalyticsEvent struct {
	ID        int64     `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	GameID    string    `json:"game_id"`
	EventType string    `json:"event_type"`
	Payload   []byte    `json:"payload"`
	CreatedAt time.Time `json:"created_at"`
}

type Game struct {
	ID            string    `json:"id"`
	Title         string    `json:"title"`
	CreatorID     string    `json:"creator_id"`
	TimeLimitSec  int32     `json:"time_limit_sec"`
	Tags          []string  `json:"tags"`
	BundleUrl     string    `json:"bundle_url"`
	BundleVersion string    `json:"bundle_version"`
	BundleHash    string    `json:"bundle_hash"`
	CreatedAt     time.Time `json:"created_at"`
}

type GlobalRankingsWeekly struct {
	WeekStart  time.Time `json:"week_start"`
	UserID     uuid.UUID `json:"user_id"`
	TotalScore int64     `json:"total_score"`
	Rank       int32     `json:"rank"`
}

type Purchase struct {
	ID           uuid.UUID  `json:"id"`
	UserID       uuid.UUID  `json:"user_id"`
	ProductID    string     `json:"product_id"`
	Platform     string     `json:"platform"`
	ReceiptToken string     `json:"receipt_token"`
	Verified     bool       `json:"verified"`
	ExpiresAt    *time.Time `json:"expires_at"`
	CreatedAt    time.Time  `json:"created_at"`
}

type ScoreAggregate struct {
	GameID    string    `json:"game_id"`
	UserID    uuid.UUID `json:"user_id"`
	BestScore int32     `json:"best_score"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Session struct {
	ID                 uuid.UUID  `json:"id"`
	UserID             uuid.UUID  `json:"user_id"`
	StartedAt          time.Time  `json:"started_at"`
	EndedAt            *time.Time `json:"ended_at"`
	RecommendedGameIds []string   `json:"recommended_game_ids"`
	DdaIntensity       int32      `json:"dda_intensity"`
}

type SessionResult struct {
	SessionID   uuid.UUID `json:"session_id"`
	GameID      string    `json:"game_id"`
	Score       int32     `json:"score"`
	PlayTimeSec float32   `json:"play_time_sec"`
	Cleared     bool      `json:"cleared"`
	SubmittedAt time.Time `json:"submitted_at"`
}

type User struct {
	ID         uuid.UUID `json:"id"`
	DeviceID   string    `json:"device_id"`
	CreatedAt  time.Time `json:"created_at"`
	LastSeenAt time.Time `json:"last_seen_at"`
}
