// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: purchases.sql

package sqlc

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const hasAdRemoval = `-- name: HasAdRemoval :one
SELECT EXISTS (
    SELECT 1 FROM purchases
    WHERE user_id = $1
      AND product_id = $2
      AND verified = true
      AND (expires_at IS NULL OR expires_at > now())
) AS owned
`

type HasAdRemovalParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ProductID string    `json:"product_id"`
}

func (q *Queries) HasAdRemoval(ctx context.Context, arg HasAdRemovalParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasAdRemoval, arg.UserID, arg.ProductID)
	var owned bool
	err := row.Scan(&owned)
	return owned, err
}

const insertPurchase = `-- name: InsertPurchase :one
INSERT INTO purchases (user_id, product_id, platform, receipt_token, verified, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (platform, receipt_token) DO UPDATE SET
    verified = EXCLUDED.verified,
    expires_at = EXCLUDED.expires_at
RETURNING id, user_id, product_id, platform, receipt_token, verified, expires_at, created_at
`

type InsertPurchaseParams struct {
	UserID       uuid.UUID  `json:"user_id"`
	ProductID    string     `json:"product_id"`
	Platform     string     `json:"platform"`
	ReceiptToken string     `json:"receipt_token"`
	Verified     bool       `json:"verified"`
	ExpiresAt    *time.Time `json:"expires_at"`
}

func (q *Queries) InsertPurchase(ctx context.Context, arg InsertPurchaseParams) (Purchase, error) {
	row := q.db.QueryRow(ctx, insertPurchase,
		arg.UserID,
		arg.ProductID,
		arg.Platform,
		arg.ReceiptToken,
		arg.Verified,
		arg.ExpiresAt,
	)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Platform,
		&i.ReceiptToken,
		&i.Verified,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActivePurchases = `-- name: ListActivePurchases :many
SELECT id, user_id, product_id, platform, receipt_token, verified, expires_at, created_at FROM purchases WHERE user_id = $1 AND verified = true
`

func (q *Queries) ListActivePurchases(ctx context.Context, userID uuid.UUID) ([]Purchase, error) {
	rows, err := q.db.Query(ctx, listActivePurchases, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Purchase{}
	for rows.Next() {
		var i Purchase
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Platform,
			&i.ReceiptToken,
			&i.Verified,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
