// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	uuid "github.com/google/uuid"
)

type Querier interface {
	CountSessionsByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, deviceID string) (User, error)
	EndSession(ctx context.Context, arg EndSessionParams) error
	GetGameByID(ctx context.Context, id string) (Game, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUserBest(ctx context.Context, arg GetUserBestParams) (ScoreAggregate, error)
	GetUserByDeviceID(ctx context.Context, deviceID string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	HasAdRemoval(ctx context.Context, arg HasAdRemovalParams) (bool, error)
	InsertAnalyticsEvent(ctx context.Context, arg InsertAnalyticsEventParams) error
	InsertPurchase(ctx context.Context, arg InsertPurchaseParams) (Purchase, error)
	InsertSessionResult(ctx context.Context, arg InsertSessionResultParams) error
	ListActivePurchases(ctx context.Context, userID uuid.UUID) ([]Purchase, error)
	ListEventsByUser(ctx context.Context, arg ListEventsByUserParams) ([]AnalyticsEvent, error)
	ListGames(ctx context.Context) ([]Game, error)
	ListGamesByTags(ctx context.Context, dollar_1 []string) ([]Game, error)
	ListGlobalTop(ctx context.Context, arg ListGlobalTopParams) ([]GlobalRankingsWeekly, error)
	ListRecentResultsByUser(ctx context.Context, arg ListRecentResultsByUserParams) ([]SessionResult, error)
	ListResultsBySession(ctx context.Context, sessionID uuid.UUID) ([]SessionResult, error)
	ListTopByGame(ctx context.Context, arg ListTopByGameParams) ([]ScoreAggregate, error)
	UpdateLastSeen(ctx context.Context, id uuid.UUID) error
	UpsertBestScore(ctx context.Context, arg UpsertBestScoreParams) error
	UpsertGame(ctx context.Context, arg UpsertGameParams) error
	UpsertWeeklyRank(ctx context.Context, arg UpsertWeeklyRankParams) error
}

var _ Querier = (*Queries)(nil)
