// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scores.sql

package sqlc

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const getUserBest = `-- name: GetUserBest :one
SELECT game_id, user_id, best_score, updated_at FROM score_aggregates WHERE game_id = $1 AND user_id = $2
`

type GetUserBestParams struct {
	GameID string    `json:"game_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUserBest(ctx context.Context, arg GetUserBestParams) (ScoreAggregate, error) {
	row := q.db.QueryRow(ctx, getUserBest, arg.GameID, arg.UserID)
	var i ScoreAggregate
	err := row.Scan(
		&i.GameID,
		&i.UserID,
		&i.BestScore,
		&i.UpdatedAt,
	)
	return i, err
}

const listGlobalTop = `-- name: ListGlobalTop :many
SELECT week_start, user_id, total_score, rank FROM global_rankings_weekly
WHERE week_start = $1
ORDER BY rank ASC
LIMIT $2
`

type ListGlobalTopParams struct {
	WeekStart time.Time `json:"week_start"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListGlobalTop(ctx context.Context, arg ListGlobalTopParams) ([]GlobalRankingsWeekly, error) {
	rows, err := q.db.Query(ctx, listGlobalTop, arg.WeekStart, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GlobalRankingsWeekly{}
	for rows.Next() {
		var i GlobalRankingsWeekly
		if err := rows.Scan(
			&i.WeekStart,
			&i.UserID,
			&i.TotalScore,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopByGame = `-- name: ListTopByGame :many
SELECT game_id, user_id, best_score, updated_at
FROM score_aggregates
WHERE game_id = $1
ORDER BY best_score DESC
LIMIT $2
`

type ListTopByGameParams struct {
	GameID string `json:"game_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListTopByGame(ctx context.Context, arg ListTopByGameParams) ([]ScoreAggregate, error) {
	rows, err := q.db.Query(ctx, listTopByGame, arg.GameID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScoreAggregate{}
	for rows.Next() {
		var i ScoreAggregate
		if err := rows.Scan(
			&i.GameID,
			&i.UserID,
			&i.BestScore,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBestScore = `-- name: UpsertBestScore :exec
INSERT INTO score_aggregates (game_id, user_id, best_score, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (game_id, user_id) DO UPDATE SET
    best_score = GREATEST(score_aggregates.best_score, EXCLUDED.best_score),
    updated_at = now()
`

type UpsertBestScoreParams struct {
	GameID    string    `json:"game_id"`
	UserID    uuid.UUID `json:"user_id"`
	BestScore int32     `json:"best_score"`
}

func (q *Queries) UpsertBestScore(ctx context.Context, arg UpsertBestScoreParams) error {
	_, err := q.db.Exec(ctx, upsertBestScore, arg.GameID, arg.UserID, arg.BestScore)
	return err
}

const upsertWeeklyRank = `-- name: UpsertWeeklyRank :exec
INSERT INTO global_rankings_weekly (week_start, user_id, total_score, rank)
VALUES ($1, $2, $3, $4)
ON CONFLICT (week_start, user_id) DO UPDATE SET
    total_score = EXCLUDED.total_score,
    rank = EXCLUDED.rank
`

type UpsertWeeklyRankParams struct {
	WeekStart  time.Time `json:"week_start"`
	UserID     uuid.UUID `json:"user_id"`
	TotalScore int64     `json:"total_score"`
	Rank       int32     `json:"rank"`
}

func (q *Queries) UpsertWeeklyRank(ctx context.Context, arg UpsertWeeklyRankParams) error {
	_, err := q.db.Exec(ctx, upsertWeeklyRank,
		arg.WeekStart,
		arg.UserID,
		arg.TotalScore,
		arg.Rank,
	)
	return err
}
