// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"

	uuid "github.com/google/uuid"
)

const countSessionsByUser = `-- name: CountSessionsByUser :one
SELECT COUNT(*) FROM sessions WHERE user_id = $1
`

func (q *Queries) CountSessionsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSessionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, recommended_game_ids, dda_intensity)
VALUES ($1, $2, $3)
RETURNING id, user_id, started_at, ended_at, recommended_game_ids, dda_intensity
`

type CreateSessionParams struct {
	UserID             uuid.UUID `json:"user_id"`
	RecommendedGameIds []string  `json:"recommended_game_ids"`
	DdaIntensity       int32     `json:"dda_intensity"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.RecommendedGameIds, arg.DdaIntensity)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.RecommendedGameIds,
		&i.DdaIntensity,
	)
	return i, err
}

const endSession = `-- name: EndSession :exec
UPDATE sessions SET ended_at = now() WHERE id = $1 AND user_id = $2
`

type EndSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) EndSession(ctx context.Context, arg EndSessionParams) error {
	_, err := q.db.Exec(ctx, endSession, arg.ID, arg.UserID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, started_at, ended_at, recommended_game_ids, dda_intensity FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.RecommendedGameIds,
		&i.DdaIntensity,
	)
	return i, err
}

const insertSessionResult = `-- name: InsertSessionResult :exec
INSERT INTO session_results (session_id, game_id, score, play_time_sec, cleared)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (session_id, game_id) DO UPDATE SET
    score = EXCLUDED.score,
    play_time_sec = EXCLUDED.play_time_sec,
    cleared = EXCLUDED.cleared,
    submitted_at = now()
`

type InsertSessionResultParams struct {
	SessionID   uuid.UUID `json:"session_id"`
	GameID      string    `json:"game_id"`
	Score       int32     `json:"score"`
	PlayTimeSec float32   `json:"play_time_sec"`
	Cleared     bool      `json:"cleared"`
}

func (q *Queries) InsertSessionResult(ctx context.Context, arg InsertSessionResultParams) error {
	_, err := q.db.Exec(ctx, insertSessionResult,
		arg.SessionID,
		arg.GameID,
		arg.Score,
		arg.PlayTimeSec,
		arg.Cleared,
	)
	return err
}

const listRecentResultsByUser = `-- name: ListRecentResultsByUser :many
SELECT sr.session_id, sr.game_id, sr.score, sr.play_time_sec, sr.cleared, sr.submitted_at FROM session_results sr
JOIN sessions s ON sr.session_id = s.id
WHERE s.user_id = $1
ORDER BY sr.submitted_at DESC
LIMIT $2
`

type ListRecentResultsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListRecentResultsByUser(ctx context.Context, arg ListRecentResultsByUserParams) ([]SessionResult, error) {
	rows, err := q.db.Query(ctx, listRecentResultsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionResult{}
	for rows.Next() {
		var i SessionResult
		if err := rows.Scan(
			&i.SessionID,
			&i.GameID,
			&i.Score,
			&i.PlayTimeSec,
			&i.Cleared,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResultsBySession = `-- name: ListResultsBySession :many
SELECT session_id, game_id, score, play_time_sec, cleared, submitted_at FROM session_results WHERE session_id = $1
`

func (q *Queries) ListResultsBySession(ctx context.Context, sessionID uuid.UUID) ([]SessionResult, error) {
	rows, err := q.db.Query(ctx, listResultsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionResult{}
	for rows.Next() {
		var i SessionResult
		if err := rows.Scan(
			&i.SessionID,
			&i.GameID,
			&i.Score,
			&i.PlayTimeSec,
			&i.Cleared,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
