// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	uuid "github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (device_id) VALUES ($1)
RETURNING id, device_id, created_at, last_seen_at
`

func (q *Queries) CreateUser(ctx context.Context, deviceID string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, deviceID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByDeviceID = `-- name: GetUserByDeviceID :one
SELECT id, device_id, created_at, last_seen_at FROM users WHERE device_id = $1
`

func (q *Queries) GetUserByDeviceID(ctx context.Context, deviceID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDeviceID, deviceID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, device_id, created_at, last_seen_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const updateLastSeen = `-- name: UpdateLastSeen :exec
UPDATE users SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) UpdateLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastSeen, id)
	return err
}
